import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import type { AuthenticatedActor } from "@trust-core/protocol";

export interface IdentityClaims { subject:string;issuer:string;displayName:string;email?:string;roles:readonly string[];workspaceIds:readonly string[];nonce:string; }
export interface OidcProvider { authorizationEndpoint():Promise<string>; exchangeCode(input:{code:string;codeVerifier:string;redirectUri:string;expectedNonce:string}):Promise<IdentityClaims>; }
export interface LoginTransaction { stateHash:string;browserBindingHash:string;nonce:string;codeVerifier:string;redirectUri:string;returnTo:string;expiresAt:string; }
export interface IdentitySessionRecord { sessionHash:string;csrfHash:string;actor:AuthenticatedActor;createdAt:string;expiresAt:string;lastSeenAt:string; }
export interface IdentityStore { saveLogin(value:LoginTransaction):Promise<void>; consumeLogin(stateHash:string):Promise<LoginTransaction|undefined>; createSession(value:IdentitySessionRecord):Promise<void>; getSession(sessionHash:string):Promise<IdentitySessionRecord|undefined>; revokeSession(sessionHash:string):Promise<void>; }
export interface OidcServiceConfig { clientId:string;redirectUri:string;sessionLifetimeMs?:number;loginLifetimeMs?:number;allowedReturnPaths?:readonly string[];roleMap?:Readonly<Record<string,AuthenticatedActor["roles"][number]>>; }
export interface OidcLoginResult { authorizationUrl:string;browserBinding:string; }
export interface OidcSessionResult { sessionId:string;csrfToken:string;actor:AuthenticatedActor;expiresAt:string;returnTo:string; }

export class OidcIdentityService {
  constructor(private readonly provider:OidcProvider,private readonly store:IdentityStore,private readonly config:OidcServiceConfig,private readonly now=()=>Date.now()){}
  async beginLogin(returnTo="/"):Promise<OidcLoginResult>{const safeReturn=this.safeReturn(returnTo),state=token(32),browserBinding=token(32),nonce=token(32),codeVerifier=token(48),challenge=base64Hash(codeVerifier),expiresAt=new Date(this.now()+(this.config.loginLifetimeMs??5*60_000)).toISOString();await this.store.saveLogin({stateHash:hash(state),browserBindingHash:hash(browserBinding),nonce,codeVerifier,redirectUri:this.config.redirectUri,returnTo:safeReturn,expiresAt});const endpoint=await this.provider.authorizationEndpoint();const url=new URL(endpoint);url.search=new URLSearchParams({response_type:"code",client_id:this.config.clientId,redirect_uri:this.config.redirectUri,scope:"openid profile email",state,nonce,code_challenge:challenge,code_challenge_method:"S256"}).toString();return{authorizationUrl:url.toString(),browserBinding};}
  async completeLogin(input:{state:string;code:string;browserBinding:string}):Promise<OidcSessionResult>{const transaction=await this.store.consumeLogin(hash(input.state));if(!transaction)throw new IdentityError("OIDC_STATE_INVALID","Login state is invalid or already used.");if(!safeEqual(transaction.browserBindingHash,hash(input.browserBinding)))throw new IdentityError("OIDC_BROWSER_BINDING_INVALID","Login callback did not originate from the initiating browser.");if(Date.parse(transaction.expiresAt)<=this.now())throw new IdentityError("OIDC_STATE_EXPIRED","Login state has expired.");const claims=await this.provider.exchangeCode({code:input.code,codeVerifier:transaction.codeVerifier,redirectUri:transaction.redirectUri,expectedNonce:transaction.nonce});if(claims.nonce!==transaction.nonce)throw new IdentityError("OIDC_NONCE_INVALID","Identity nonce validation failed.");const actor=this.mapActor(claims),sessionId=token(32),csrfToken=token(24),createdAt=new Date(this.now()).toISOString(),expiresAt=new Date(this.now()+(this.config.sessionLifetimeMs??30*60_000)).toISOString();await this.store.createSession({sessionHash:hash(sessionId),csrfHash:hash(csrfToken),actor,createdAt,expiresAt,lastSeenAt:createdAt});return{sessionId,csrfToken,actor,expiresAt,returnTo:transaction.returnTo};}
  async authenticateSession(sessionId:string,csrfToken:string|undefined,mutation:boolean):Promise<AuthenticatedActor|undefined>{const record=await this.store.getSession(hash(sessionId));if(!record||Date.parse(record.expiresAt)<=this.now()||mutation&&!csrfToken||mutation&&!safeEqual(record.csrfHash,hash(csrfToken!)))return undefined;return record.actor;}
  revokeSession(sessionId:string):Promise<void>{return this.store.revokeSession(hash(sessionId));}
  private mapActor(claims:IdentityClaims):AuthenticatedActor{const roleMap=this.config.roleMap??{owner:"owner",admin:"admin",editor:"editor",recovery_operator:"recovery_operator",auditor:"auditor"};const roles=[...new Set(claims.roles.map(role=>roleMap[role]).filter((role):role is AuthenticatedActor["roles"][number]=>!!role))];if(roles.length===0||claims.workspaceIds.length===0)throw new IdentityError("OIDC_CLAIMS_DENIED","Identity has no permitted Trust Core role or workspace.");return{id:`${claims.issuer}#${claims.subject}`,displayName:claims.displayName,roles,workspaceIds:[...new Set(claims.workspaceIds)]};}
  private safeReturn(value:string):string{const allowed=this.config.allowedReturnPaths??["/"];if(!value.startsWith("/")||value.startsWith("//")||!allowed.some(prefix=>value===prefix||value.startsWith(`${prefix}/`)))return "/";return value;}
}
export class IdentityError extends Error { constructor(readonly code:string,message:string){super(message);this.name="IdentityError";} }
const token=(bytes:number)=>randomBytes(bytes).toString("base64url");
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const base64Hash=(value:string)=>createHash("sha256").update(value).digest("base64url");
function safeEqual(a:string,b:string):boolean{const left=Buffer.from(a),right=Buffer.from(b);return left.byteLength===right.byteLength&&timingSafeEqual(left,right);}
