import { createRemoteJWKSet, jwtVerify } from "jose";
import type { IdentityClaims, OidcProvider } from "./oidc.js";
export interface OidcProviderConfig { issuer:string;clientId:string;clientSecret?:string;roleClaim?:string;workspaceClaim?:string;allowedAlgorithms?:readonly string[]; }
interface Discovery { issuer:string;authorization_endpoint:string;token_endpoint:string;jwks_uri:string; }
export class StandardsOidcProvider implements OidcProvider {
  private discovery?:Promise<Discovery>;
  constructor(private readonly config:OidcProviderConfig,private readonly fetcher:typeof fetch=fetch) { if(!config.issuer.startsWith("https://"))throw new Error("OIDC issuer must use HTTPS."); }
  async authorizationEndpoint():Promise<string>{return(await this.metadata()).authorization_endpoint;}
  async exchangeCode(input:{code:string;codeVerifier:string;redirectUri:string;expectedNonce:string}):Promise<IdentityClaims>{const metadata=await this.metadata();const body=new URLSearchParams({grant_type:"authorization_code",code:input.code,redirect_uri:input.redirectUri,client_id:this.config.clientId,code_verifier:input.codeVerifier});const headers:Record<string,string>={"content-type":"application/x-www-form-urlencoded","accept":"application/json"};if(this.config.clientSecret)headers.authorization=`Basic ${Buffer.from(`${this.config.clientId}:${this.config.clientSecret}`).toString("base64")}`;const response=await this.fetcher(metadata.token_endpoint,{method:"POST",headers,body});if(!response.ok)throw new Error(`OIDC token exchange failed (${response.status}).`);const tokens=await response.json() as {id_token?:string};if(!tokens.id_token)throw new Error("OIDC token response omitted id_token.");const verified=await jwtVerify(tokens.id_token,createRemoteJWKSet(new URL(metadata.jwks_uri)),{issuer:this.config.issuer,audience:this.config.clientId,algorithms:[...(this.config.allowedAlgorithms??["RS256","PS256","ES256"])]});const p=verified.payload;if(p.nonce!==input.expectedNonce)throw new Error("OIDC nonce validation failed.");if(!p.sub)throw new Error("OIDC ID token omitted subject.");const roles=claimArray(p[this.config.roleClaim??"roles"]),workspaces=claimArray(p[this.config.workspaceClaim??"trust_workspaces"]);return{subject:p.sub,issuer:p.iss??this.config.issuer,displayName:typeof p.name==="string"?p.name:typeof p.email==="string"?p.email:p.sub,...(typeof p.email==="string"?{email:p.email}:{}),roles,workspaceIds:workspaces,nonce:String(p.nonce)};}
  private metadata():Promise<Discovery>{return this.discovery??=this.loadMetadata();}
  private async loadMetadata():Promise<Discovery>{const url=`${this.config.issuer.replace(/\/$/,"")}/.well-known/openid-configuration`;const response=await this.fetcher(url,{headers:{accept:"application/json"}});if(!response.ok)throw new Error(`OIDC discovery failed (${response.status}).`);const value=await response.json() as Partial<Discovery>;if(value.issuer!==this.config.issuer||!value.authorization_endpoint||!value.token_endpoint||!value.jwks_uri)throw new Error("OIDC discovery metadata is invalid.");for(const endpoint of [value.authorization_endpoint,value.token_endpoint,value.jwks_uri])if(!endpoint.startsWith("https://"))throw new Error("OIDC endpoints must use HTTPS.");return value as Discovery;}
}
function claimArray(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):typeof value==="string"?value.split(/[ ,]+/).filter(Boolean):[];}
