import type {
  FieldDefinition,
  ResourceTypeDefinition,
  SchemaPackageManifest,
} from "./types.js";

export interface GeneratedTypeScript {
  readonly packageKey: string;
  readonly source: string;
}

export function generateTypeScriptTypes(
  manifest: SchemaPackageManifest,
): GeneratedTypeScript {
  const packageKey = `${manifest.namespace}/${manifest.name}/${manifest.version}`;
  const resources = [...manifest.resourceTypes].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const declarations = resources.map(resourceDeclaration).join("\n\n");
  const names = resources.map(({ name }) => JSON.stringify(name)).join(" | ");
  const mapMembers = resources
    .map(({ name }) => `  readonly ${JSON.stringify(name)}: ${name};`)
    .join("\n");
  const source = `/* Generated by @trust-core/schema-registry from ${packageKey}. Do not edit. */

export const schemaPackageKey = ${JSON.stringify(packageKey)} as const;
export type ResourceType = ${names || "never"};

${declarations}

export interface ResourcePayloadByType {
${mapMembers}
}

export type ResourcePayload<T extends ResourceType> =
  ResourcePayloadByType[T];
`;
  return { packageKey, source };
}

function resourceDeclaration(resource: ResourceTypeDefinition): string {
  const fields = Object.entries(resource.fields)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, field]) => fieldDeclaration(name, field))
    .join("\n");
  const additional =
    resource.additionalFields === "preserve"
      ? "\n  readonly [field: string]: unknown;"
      : "";
  return `export interface ${resource.name} {
${fields}${additional}
}`;
}

function fieldDeclaration(name: string, field: FieldDefinition): string {
  const optional = field.required ? "" : "?";
  return `  readonly ${JSON.stringify(name)}${optional}: ${fieldType(field)};`;
}

function fieldType(field: FieldDefinition): string {
  switch (field.kind) {
    case "string":
    case "timestamp":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "object":
      return "Readonly<Record<string, unknown>>";
    case "array":
      return "readonly unknown[]";
    default:
      return assertNever(field.kind);
  }
}

function assertNever(value: never): never {
  throw new Error(`Unhandled field kind: ${String(value)}`);
}
