import { ResourceHistoryService, type ObjectIngestResult, type ObjectIngestService } from "@trust-core/operations";
import { PostgresHistoryRepository, inTransaction, type DatabasePool } from "@trust-core/persistence-postgres";
import type { AuthenticatedActor, DeleteResourceCommand, DeleteResourceResult, HistorySnapshot, RecoverableItem, RestoreResourceCommand, RevisionCommand, RevisionCommandResult, TrustEventSummary } from "@trust-core/protocol";
import type { RunVerificationCommand,VerificationRunResult } from "@trust-core/protocol";
import type { BlobVerificationService } from "@trust-core/verification";
import type { CommandProvider, ObjectIngestCommand } from "./app.js";

export class PostgresCommandProvider implements CommandProvider {
  private readonly history:ResourceHistoryService;
  constructor(private readonly pool:DatabasePool,private readonly verification?:BlobVerificationService,private readonly ingest?:ObjectIngestService){this.history=new ResourceHistoryService(new PostgresHistoryRepository(pool));}
  async getHistory(workspaceId:string):Promise<HistorySnapshot>{return inTransaction(this.pool,async db=>{await db.query("SELECT set_config('trust.workspace_id',$1,true)",[workspaceId]);const deleted=await db.query<RecoverableRow>("SELECT t.id AS tombstone_id,t.workspace_id,t.dataset_id,t.subject_id AS resource_id,r.title AS resource_title,r.resource_type,t.deleted_at,t.recover_until,t.deleted_by,t.prior_revision_id FROM tombstones t JOIN resources r ON r.id=t.subject_id::uuid AND r.workspace_id=t.workspace_id WHERE t.workspace_id=$1 AND t.subject_kind='resource' AND t.restored_at IS NULL AND t.purge_state<>'purged' ORDER BY t.deleted_at DESC LIMIT 100",[workspaceId]);const events=await db.query<EventRow>("SELECT id,action,subject_id,actor_id,occurred_at,metadata_json FROM audit_events WHERE workspace_id=$1 ORDER BY occurred_at DESC,id DESC LIMIT 100",[workspaceId]);return{recoverable:deleted.rows.map(mapRecoverable),events:events.rows.map(mapEvent)};});}
  async createRevision(resourceId:string,actor:AuthenticatedActor,command:RevisionCommand):Promise<RevisionCommandResult>{const r=await this.history.createRevision({...command,resourceId,actorId:actor.id});return revisionResult(r);}
  async deleteResource(resourceId:string,actor:AuthenticatedActor,command:DeleteResourceCommand):Promise<DeleteResourceResult>{const t=await this.history.deleteResource({workspaceId:command.workspaceId,resourceId,expectedRevisionId:command.expectedRevisionId,actorId:actor.id,recoverUntil:command.recoverUntil});return{resourceId,tombstoneId:t.id,deletedAt:t.deletedAt,recoverUntil:t.recoverUntil};}
  async restoreResource(resourceId:string,actor:AuthenticatedActor,command:RestoreResourceCommand):Promise<RevisionCommandResult>{return revisionResult(await this.history.restoreResource({workspaceId:command.workspaceId,resourceId,actorId:actor.id,...(command.changeNote?{changeNote:command.changeNote}:{})}));}
  async runVerification(_actor:AuthenticatedActor,command:RunVerificationCommand):Promise<VerificationRunResult>{if(!this.verification)throw new Error("Object verification adapter is not configured.");return this.verification.run(command);}
  async ingestObject(actor:AuthenticatedActor,command:ObjectIngestCommand):Promise<ObjectIngestResult>{if(!this.ingest)throw new Error("Object ingest adapter is not configured.");if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(command.bytesBase64))throw new Error("Object bytes are not valid base64.");return this.ingest.ingest({workspaceId:command.workspaceId,actorId:actor.id,idempotencyKey:command.idempotencyKey,mediaType:command.mediaType,bytes:Buffer.from(command.bytesBase64,"base64")});}
}
function revisionResult(r:{resourceId:string;id:string;revisionNumber:number;source:RevisionCommandResult["source"];createdAt:string}):RevisionCommandResult{return{resourceId:r.resourceId,revisionId:r.id,revisionNumber:r.revisionNumber,source:r.source,createdAt:r.createdAt};}
interface RecoverableRow{tombstone_id:string;workspace_id:string;dataset_id:string;resource_id:string;resource_title:string|null;resource_type:string;deleted_at:string|Date;recover_until:string|Date|null;deleted_by:string;prior_revision_id:string|null;}
interface EventRow{id:string;action:string;subject_id:string;actor_id:string;occurred_at:string|Date;metadata_json:Record<string,unknown>;}
const iso=(v:string|Date)=>new Date(v).toISOString();
function mapRecoverable(r:RecoverableRow):RecoverableItem{return{tombstoneId:r.tombstone_id,workspaceId:r.workspace_id,datasetId:r.dataset_id,resourceId:r.resource_id,resourceTitle:r.resource_title,resourceType:r.resource_type,deletedAt:iso(r.deleted_at),recoverUntil:r.recover_until?iso(r.recover_until):null,deletedBy:r.deleted_by,priorRevisionId:r.prior_revision_id};}
function mapEvent(r:EventRow):TrustEventSummary{return{id:r.id,action:r.action,subjectId:r.subject_id,actorId:r.actor_id,occurredAt:iso(r.occurred_at),metadata:r.metadata_json};}
