/* Generated by @trust-core/schema-registry from app/ivans-diary/1.0.0. Do not edit. */

export const schemaPackageKey = "app/ivans-diary/1.0.0" as const;
export type ResourceType = "Audio" | "Bookmark" | "Diary" | "Drawing" | "Entry" | "JournalPage" | "Photo" | "Sketchbook" | "SketchPage" | "TextBlock";

export interface Audio {
  readonly "blobSha256": string;
  readonly "createdAt": string;
  readonly "durationSeconds": number;
  readonly "mediaType": string;
  readonly "modifiedAt": string;
  readonly [field: string]: unknown;
}

export interface Bookmark {
  readonly "createdAt": string;
  readonly "label": string;
  readonly "modifiedAt": string;
  readonly [field: string]: unknown;
}

export interface Diary {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "title": string;
  readonly [field: string]: unknown;
}

export interface Drawing {
  readonly "blobSha256": string;
  readonly "createdAt": string;
  readonly "mediaType": string;
  readonly "modifiedAt": string;
  readonly [field: string]: unknown;
}

export interface Entry {
  readonly "createdAt": string;
  readonly "entryDate": string;
  readonly "favourite"?: boolean;
  readonly "modifiedAt": string;
  readonly "title": string;
  readonly [field: string]: unknown;
}

export interface JournalPage {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "pageNumber": number;
  readonly "title"?: string;
  readonly [field: string]: unknown;
}

export interface Photo {
  readonly "blobSha256": string;
  readonly "caption"?: string;
  readonly "createdAt": string;
  readonly "mediaType": string;
  readonly "modifiedAt": string;
  readonly [field: string]: unknown;
}

export interface Sketchbook {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "title": string;
  readonly [field: string]: unknown;
}

export interface SketchPage {
  readonly "canvasHeight": number;
  readonly "canvasWidth": number;
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "pageNumber": number;
  readonly [field: string]: unknown;
}

export interface TextBlock {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "source": string;
  readonly "text": string;
  readonly [field: string]: unknown;
}

export interface ResourcePayloadByType {
  readonly "Audio": Audio;
  readonly "Bookmark": Bookmark;
  readonly "Diary": Diary;
  readonly "Drawing": Drawing;
  readonly "Entry": Entry;
  readonly "JournalPage": JournalPage;
  readonly "Photo": Photo;
  readonly "Sketchbook": Sketchbook;
  readonly "SketchPage": SketchPage;
  readonly "TextBlock": TextBlock;
}

export type ResourcePayload<T extends ResourceType> =
  ResourcePayloadByType[T];
