import { createHash, randomUUID } from "node:crypto";
import type { BlobObject } from "@trust-core/core";
import type { ObjectStorage } from "@trust-core/storage";
export type VerificationLevel="metadata"|"full_blob";
export type VerificationStatus="running"|"passed"|"failed"|"degraded";
export interface VerificationIssue { code:string;severity:"warning"|"error"|"critical";subjectKind:"blob"|"resource"|"storage";subjectId:string;message:string;expected?:string|number;actual?:string|number|null; }
export interface BlobVerificationResult { blobId:string;level:VerificationLevel;status:"passed"|"failed";checkedAt:string;bytesRead:number;issues:readonly VerificationIssue[]; }
export interface VerificationRun { id:string;workspaceId:string;level:VerificationLevel;status:VerificationStatus;startedAt:string;completedAt:string;objectsChecked:number;bytesRead:number;issues:readonly VerificationIssue[]; }
export interface VerificationCatalog { listBlobs(workspaceId:string):Promise<readonly BlobObject[]>; recordRun(run:VerificationRun):Promise<void>; setBlobVerification(workspaceId:string,blobId:string,state:BlobObject["verificationState"]):Promise<void>; }
export class BlobVerificationService {
  constructor(private readonly storage:ObjectStorage,private readonly catalog:VerificationCatalog,private readonly now:()=>string=()=>new Date().toISOString(),private readonly nextId:()=>string=()=>randomUUID()){}
  async run(input:{workspaceId:string;level:VerificationLevel}):Promise<VerificationRun>{const startedAt=this.now(),blobs=await this.catalog.listBlobs(input.workspaceId),results:BlobVerificationResult[]=[];for(const blob of blobs){const result=await this.verifyBlob(blob,input.level);results.push(result);await this.catalog.setBlobVerification(input.workspaceId,blob.id,result.status==="passed"?"verified":"failed");}const issues=results.flatMap(result=>result.issues),status:VerificationStatus=issues.some(issue=>issue.severity==="critical"||issue.severity==="error")?"failed":issues.length?"degraded":"passed";const run:VerificationRun={id:this.nextId(),workspaceId:input.workspaceId,level:input.level,status,startedAt,completedAt:this.now(),objectsChecked:results.length,bytesRead:results.reduce((sum,result)=>sum+result.bytesRead,0),issues};await this.catalog.recordRun(run);return run;}
  async verifyBlob(blob:BlobObject,level:VerificationLevel):Promise<BlobVerificationResult>{const checkedAt=this.now(),issues:VerificationIssue[]=[];let metadata;try{metadata=await this.storage.head({key:blob.storageKey});}catch(error){issues.push({code:"BLOB_MISSING_OR_INACCESSIBLE",severity:"critical",subjectKind:"blob",subjectId:blob.id,message:error instanceof Error?error.message:"Canonical object is missing or inaccessible.",expected:blob.storageKey,actual:null});return{blobId:blob.id,level,status:"failed",checkedAt,bytesRead:0,issues};}if(metadata.key!==blob.storageKey)issues.push(issue(blob,"STORAGE_KEY_MISMATCH","error","Storage returned a different object key.",blob.storageKey,metadata.key));if(metadata.byteLength!==blob.byteLength)issues.push(issue(blob,"BLOB_LENGTH_MISMATCH","critical","Stored byte length differs from canonical metadata.",blob.byteLength,metadata.byteLength));if(metadata.sha256&&metadata.sha256!==blob.sha256)issues.push(issue(blob,"STORED_HASH_METADATA_MISMATCH","critical","Storage hash metadata differs from the canonical hash.",blob.sha256,metadata.sha256));if(level==="metadata")return{blobId:blob.id,level,status:issues.length?"failed":"passed",checkedAt,bytesRead:0,issues};let bytesRead=0;const hash=createHash("sha256");try{const stream=await this.storage.openReadStream({key:blob.storageKey});for await(const chunk of stream){const bytes=Buffer.from(chunk);bytesRead+=bytes.byteLength;hash.update(bytes);}}catch(error){issues.push({code:"BLOB_STREAM_FAILED",severity:"critical",subjectKind:"storage",subjectId:blob.id,message:error instanceof Error?error.message:"Object stream failed.",expected:blob.byteLength,actual:bytesRead});return{blobId:blob.id,level,status:"failed",checkedAt,bytesRead,issues};}const digest=hash.digest("hex");if(bytesRead!==blob.byteLength)issues.push(issue(blob,"FULL_LENGTH_MISMATCH","critical","Streamed byte count differs from canonical metadata.",blob.byteLength,bytesRead));if(digest!==blob.sha256)issues.push(issue(blob,"FULL_HASH_MISMATCH","critical","Streamed SHA-256 differs from the canonical hash.",blob.sha256,digest));return{blobId:blob.id,level,status:issues.length?"failed":"passed",checkedAt,bytesRead,issues};}
}
function issue(blob:BlobObject,code:string,severity:VerificationIssue["severity"],message:string,expected:string|number,actual:string|number):VerificationIssue{return{code,severity,subjectKind:"blob",subjectId:blob.id,message,expected,actual};}
