import { createHash } from "node:crypto";
import { describe,expect,it } from "vitest";
import { IdentityError,OidcIdentityService,type IdentitySessionRecord,type IdentityStore,type LoginTransaction,type OidcProvider } from "../src/index.js";
class MemoryStore implements IdentityStore { login=new Map<string,LoginTransaction>();sessions=new Map<string,IdentitySessionRecord>();async saveLogin(v:LoginTransaction){this.login.set(v.stateHash,v);}async consumeLogin(key:string){const v=this.login.get(key);this.login.delete(key);return v;}async createSession(v:IdentitySessionRecord){this.sessions.set(v.sessionHash,v);}async getSession(key:string){return this.sessions.get(key);}async revokeSession(key:string){this.sessions.delete(key);} }
class FakeProvider implements OidcProvider { nonce="";async authorizationEndpoint(){return"https://identity.example/authorize";}async exchangeCode(input:{expectedNonce:string}){this.nonce=input.expectedNonce;return{subject:"ben",issuer:"https://identity.example",displayName:"Ben",roles:["studio-admin"],workspaceIds:["workspace"],nonce:this.nonce};} }
const sha=(v:string)=>createHash("sha256").update(v).digest("hex");
describe("OIDC identity boundary",()=>{
  it("uses code flow with PKCE, browser binding, one-time state and nonce then creates a hashed session",async()=>{const store=new MemoryStore(),provider=new FakeProvider(),service=new OidcIdentityService(provider,store,{clientId:"client",redirectUri:"https://trust.example/callback",roleMap:{"studio-admin":"admin"}},()=>1_000);const begun=await service.beginLogin("/");const url=new URL(begun.authorizationUrl);expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("code_challenge_method")).toBe("S256");const state=url.searchParams.get("state")!;const complete=await service.completeLogin({state,code:"code",browserBinding:begun.browserBinding});expect(complete.actor.roles).toEqual(["admin"]);expect(store.sessions.has(sha(complete.sessionId))).toBe(true);expect(await service.authenticateSession(complete.sessionId,complete.csrfToken,true)).toEqual(complete.actor);await expect(service.completeLogin({state,code:"replay",browserBinding:begun.browserBinding})).rejects.toMatchObject({code:"OIDC_STATE_INVALID"});const swapped=await service.beginLogin("/");await expect(service.completeLogin({state:new URL(swapped.authorizationUrl).searchParams.get("state")!,code:"code",browserBinding:"wrong-browser"})).rejects.toMatchObject({code:"OIDC_BROWSER_BINDING_INVALID"});});
  it("rejects identities without mapped roles and prevents open redirects",async()=>{const store=new MemoryStore();const provider:OidcProvider={authorizationEndpoint:async()=>"https://identity.example/authorize",exchangeCode:async input=>({subject:"x",issuer:"https://identity.example",displayName:"X",roles:["unknown"],workspaceIds:["workspace"],nonce:input.expectedNonce})};const service=new OidcIdentityService(provider,store,{clientId:"client",redirectUri:"https://trust.example/callback"},()=>1_000);const begun=await service.beginLogin("//evil.example");const state=new URL(begun.authorizationUrl).searchParams.get("state")!;await expect(service.completeLogin({state,code:"code",browserBinding:begun.browserBinding})).rejects.toBeInstanceOf(IdentityError);});
});
