import { Readable } from "node:stream";
import { describe,expect,it } from "vitest";
import type { BlobObject } from "@trust-core/core";
import type { ObjectLocator,ObjectMetadata,ObjectStorage,StoredObject,TemporaryObject } from "@trust-core/storage";
import { BlobVerificationService,type VerificationCatalog,type VerificationRun } from "../src/index.js";
class Storage implements ObjectStorage { bytes=Buffer.from("trusted bytes");missing=false;async createTemporaryUpload():Promise<TemporaryObject>{throw new Error("unused");}async writeTemporary():Promise<ObjectMetadata>{throw new Error("unused");}async commitImmutable():Promise<StoredObject>{throw new Error("unused");}async openReadStream(){if(this.missing)throw new Error("missing");return Readable.from(this.bytes);}async head(input:ObjectLocator){if(this.missing)throw new Error("missing");return{key:input.key,byteLength:this.bytes.length,mediaType:"text/plain"};}async exists(){return!this.missing;}async deleteTemporary(){} }
const blob:BlobObject={id:"blob",workspaceId:"workspace",sha256:"6acd7c3c149b0fdbc542a20bb7ece8164ebf4b78148c3f65c2fddf208cc74e35",byteLength:13,mediaType:"text/plain",storageProvider:"memory",storageKey:"workspace/objects/blob",verificationState:"pending",createdAt:"2026-01-01T00:00:00.000Z"};
class Catalog implements VerificationCatalog { runs:VerificationRun[]=[];state="pending";constructor(readonly blobs:BlobObject[]){}async listBlobs(){return this.blobs;}async recordRun(run:VerificationRun){this.runs.push(run);}async setBlobVerification(_w:string,_b:string,state:BlobObject["verificationState"]){this.state=state;} }
describe("full-byte verification",()=>{it("distinguishes metadata checks from streaming hash verification",async()=>{const storage=new Storage(),catalog=new Catalog([blob]),service=new BlobVerificationService(storage,catalog,()=>"2026-01-02T00:00:00.000Z",()=>"run");const metadata=await service.run({workspaceId:"workspace",level:"metadata"});expect(metadata.bytesRead).toBe(0);expect(metadata.status).toBe("passed");const full=await service.run({workspaceId:"workspace",level:"full_blob"});expect(full.bytesRead).toBe(13);expect(full.status).toBe("passed");expect(catalog.state).toBe("verified");});it("reports corruption and missing canonical objects as critical failures",async()=>{const storage=new Storage();storage.bytes=Buffer.from("tampered bytes");const catalog=new Catalog([blob]),service=new BlobVerificationService(storage,catalog);const corrupt=await service.run({workspaceId:"workspace",level:"full_blob"});expect(corrupt.status).toBe("failed");expect(corrupt.issues.map(i=>i.code)).toContain("FULL_HASH_MISMATCH");storage.missing=true;const missing=await service.run({workspaceId:"workspace",level:"full_blob"});expect(missing.issues[0]?.code).toBe("BLOB_MISSING_OR_INACCESSIBLE");expect(catalog.state).toBe("failed");});});
