/* Generated by @trust-core/schema-registry from app/wesketch/1.0.0. Do not edit. */

export const schemaPackageKey = "app/wesketch/1.0.0" as const;
export type ResourceType = "Canvas" | "ConversationTurn" | "GeneratedImage" | "GenerationRequest" | "Layer" | "Placement" | "Project" | "SelectionMask" | "StrokeDocument";

export interface Canvas {
  readonly "background": string;
  readonly "createdAt": string;
  readonly "height": number;
  readonly "layerOrder": readonly unknown[];
  readonly "modifiedAt": string;
  readonly "width": number;
}

export interface ConversationTurn {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "role": string;
  readonly "sequence": number;
  readonly "text": string;
}

export interface GeneratedImage {
  readonly "blobSha256": string;
  readonly "createdAt": string;
  readonly "generationStatus": string;
  readonly "height": number;
  readonly "mediaType": string;
  readonly "modifiedAt": string;
  readonly "width": number;
}

export interface GenerationRequest {
  readonly "createdAt": string;
  readonly "model": string;
  readonly "modifiedAt": string;
  readonly "negativePrompt": string;
  readonly "prompt": string;
  readonly "requestSeed": number;
  readonly "settings": Readonly<Record<string, unknown>>;
}

export interface Layer {
  readonly "blendMode": string;
  readonly "createdAt": string;
  readonly "layerKind": string;
  readonly "modifiedAt": string;
  readonly "name": string;
  readonly "opacity": number;
}

export interface Placement {
  readonly "compositeMode": string;
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "transform": Readonly<Record<string, unknown>>;
}

export interface Project {
  readonly "createdAt": string;
  readonly "modifiedAt": string;
  readonly "name": string;
}

export interface SelectionMask {
  readonly "blobSha256": string;
  readonly "bounds": Readonly<Record<string, unknown>>;
  readonly "createdAt": string;
  readonly "featherPixels": number;
  readonly "modifiedAt": string;
}

export interface StrokeDocument {
  readonly "blobSha256": string;
  readonly "createdAt": string;
  readonly "mediaType": string;
  readonly "modifiedAt": string;
  readonly "strokeCount": number;
}

export interface ResourcePayloadByType {
  readonly "Canvas": Canvas;
  readonly "ConversationTurn": ConversationTurn;
  readonly "GeneratedImage": GeneratedImage;
  readonly "GenerationRequest": GenerationRequest;
  readonly "Layer": Layer;
  readonly "Placement": Placement;
  readonly "Project": Project;
  readonly "SelectionMask": SelectionMask;
  readonly "StrokeDocument": StrokeDocument;
}

export type ResourcePayload<T extends ResourceType> =
  ResourcePayloadByType[T];
