import { hostname } from "node:os";
import { Pool } from "pg";
import { PostgresOutboxStore,PostgresReconciliationCatalog,type DatabasePool,type QueryResult,type TransactionClient } from "@trust-core/persistence-postgres";
import { ReconciliationWorker,createReconciliationHandlers } from "@trust-core/reconciliation";
import { MinioObjectStorage } from "@trust-core/storage-minio";
const databaseUrl=required("DATABASE_URL"),poolSource=new Pool({connectionString:databaseUrl,max:5}),pool=adaptPool(poolSource),storage=new MinioObjectStorage({endpoint:required("TRUST_STORAGE_ENDPOINT"),region:process.env.TRUST_STORAGE_REGION??"us-east-1",bucket:required("TRUST_STORAGE_BUCKET"),accessKeyId:required("TRUST_STORAGE_ACCESS_KEY"),secretAccessKey:required("TRUST_STORAGE_SECRET_KEY"),forcePathStyle:process.env.TRUST_STORAGE_FORCE_PATH_STYLE!=="false"}),workspaceId=process.env.TRUST_WORKSPACE_ID,worker=new ReconciliationWorker(new PostgresOutboxStore(pool),createReconciliationHandlers(storage,new PostgresReconciliationCatalog(pool)),{workerId:`${hostname()}:${process.pid}`,...(workspaceId?{workspaceId}:{}),maxAttempts:Number(process.env.TRUST_WORKER_MAX_ATTEMPTS??5),batchSize:Number(process.env.TRUST_WORKER_BATCH_SIZE??25),leaseMs:Number(process.env.TRUST_WORKER_LEASE_MS??30_000),concurrency:Number(process.env.TRUST_WORKER_CONCURRENCY??4)});
async function run(){const result=await worker.runOnce();process.stdout.write(`${JSON.stringify({at:new Date().toISOString(),...result})}\n`);}
if(process.argv.includes("--once")){await run();await pool.end();}else{const interval=Number(process.env.TRUST_WORKER_INTERVAL_MS??5_000);let stopping=false,inFlight:Promise<void>|undefined,timer:NodeJS.Timeout|undefined;const loop=async()=>{if(stopping)return;inFlight=run().catch(error=>{process.stderr.write(`${error instanceof Error?error.stack:String(error)}\n`);});await inFlight;inFlight=undefined;if(!stopping)timer=setTimeout(()=>void loop(),interval);};const shutdown=async()=>{if(stopping)return;stopping=true;if(timer)clearTimeout(timer);await inFlight;await pool.end();};process.once("SIGTERM",()=>void shutdown());process.once("SIGINT",()=>void shutdown());await loop();}
function required(name:string):string{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value;}
function adaptPool(source:Pool):DatabasePool{const query=async<Row>(text:string,values?:readonly unknown[]):Promise<QueryResult<Row>>=>{const result=await source.query(text,values?[...values]:undefined);return{rows:result.rows as Row[],rowCount:result.rowCount};};return{query,async connect(){const client=await source.connect();return{query:async<Row>(text:string,values?:readonly unknown[])=>{const result=await client.query(text,values?[...values]:undefined);return{rows:result.rows as Row[],rowCount:result.rowCount};},release:()=>client.release()} satisfies TransactionClient;},end:()=>source.end()};}
