import type { OutboxEvent,OutboxStore } from "@trust-core/reconciliation";
import { inTransaction,type DatabasePool,type Queryable } from "./db.js";
export class PostgresOutboxStore implements OutboxStore {
  constructor(private readonly pool:DatabasePool){}
  claim(input:{workerId:string;workspaceId?:string;limit:number;leaseUntil:string;now:string}):Promise<readonly OutboxEvent[]>{return inTransaction(this.pool,async db=>{if(input.workspaceId)await scope(db,input.workspaceId);const scoped=Boolean(input.workspaceId),r=await db.query<OutboxRow>(`WITH candidates AS (SELECT id FROM outbox_events WHERE ${scoped?"workspace_id=$1 AND ":""}processed_at IS NULL AND quarantined_at IS NULL AND available_at<=$${scoped?2:1} AND (locked_until IS NULL OR locked_until<$${scoped?2:1}) ORDER BY available_at,id FOR UPDATE SKIP LOCKED LIMIT $${scoped?3:2}) UPDATE outbox_events e SET locked_by=$${scoped?4:3},locked_until=$${scoped?5:4} FROM candidates c WHERE e.id=c.id RETURNING e.id,e.workspace_id,e.operation_id,e.event_type,e.payload_json,e.available_at,e.attempt_count`,scoped?[input.workspaceId,input.now,input.limit,input.workerId,input.leaseUntil]:[input.now,input.limit,input.workerId,input.leaseUntil]);return r.rows.map(mapEvent);});}
  complete(workspaceId:string,eventId:string,workerId:string,processedAt:string):Promise<void>{return inTransaction(this.pool,async db=>{await scope(db,workspaceId);await changed(db,"UPDATE outbox_events SET processed_at=$3,locked_by=NULL,locked_until=NULL,last_error=NULL WHERE id=$1 AND locked_by=$2 AND processed_at IS NULL AND locked_until>=$3",[eventId,workerId,processedAt]);});}
  retry(workspaceId:string,eventId:string,workerId:string,input:{attemptCount:number;availableAt:string;failedAt:string;error:string}):Promise<void>{return inTransaction(this.pool,async db=>{await scope(db,workspaceId);await changed(db,"UPDATE outbox_events SET attempt_count=$3,available_at=$4,last_error=$6,locked_by=NULL,locked_until=NULL WHERE id=$1 AND locked_by=$2 AND processed_at IS NULL AND locked_until>=$5",[eventId,workerId,input.attemptCount,input.availableAt,input.failedAt,input.error]);});}
  quarantine(workspaceId:string,eventId:string,workerId:string,input:{attemptCount:number;quarantinedAt:string;reason:string}):Promise<void>{return inTransaction(this.pool,async db=>{await scope(db,workspaceId);const event=await db.query<{operation_id:string;event_type:string}>("UPDATE outbox_events SET attempt_count=$3,quarantined_at=$4,quarantine_reason=$5,last_error=$5,locked_by=NULL,locked_until=NULL WHERE id=$1 AND locked_by=$2 AND processed_at IS NULL AND locked_until>=$4 RETURNING operation_id,event_type",[eventId,workerId,input.attemptCount,input.quarantinedAt,input.reason]);const row=event.rows[0];if(!row)throw new Error("Outbox lease was lost or event was already handled.");await db.query("INSERT INTO reconciliation_incidents (workspace_id,operation_id,severity,code,message,metadata_json) VALUES ($1,$2,'critical','OUTBOX_EVENT_QUARANTINED',$3,$4::jsonb)",[workspaceId,row.operation_id,input.reason,JSON.stringify({eventId,eventType:row.event_type,attemptCount:input.attemptCount})]);});}
}
async function changed(db:Queryable,sql:string,values:readonly unknown[]){const r=await db.query(sql,values);if(r.rowCount!==1)throw new Error("Outbox lease was lost or event was already handled.");}
async function scope(db:Queryable,workspaceId:string){await db.query("SELECT set_config('trust.workspace_id',$1,true)",[workspaceId]);}
interface OutboxRow{id:string;workspace_id:string;operation_id:string;event_type:string;payload_json:Record<string,unknown>;available_at:string|Date;attempt_count:number;}
function mapEvent(r:OutboxRow):OutboxEvent{return{id:r.id,workspaceId:r.workspace_id,operationId:r.operation_id,eventType:r.event_type,payload:r.payload_json,availableAt:new Date(r.available_at).toISOString(),attemptCount:r.attempt_count};}
